### PR TITLE
Fix std::result_of removed in C++20

### PR DESCRIPTION
**Pull request by Asaaj**
Fix for #530, intended to be as minimal as possible. Further testing is required, but I wanted to get this in for discussion.

### CODE REVIEW

**Comment by Asaaj** [comment]
I wanted a simpler change than #545, which apparently failed. This seems safer to me

**Comment by Asaaj** [comment]
I've never worked with AppVeyor before, but is it reasonably straightforward to get it building with VS2019? Or is RxCpp not claiming to support that version of VS? I can guess what changes are required in appveyor.yml, but I'm not sure the protocol here.

**Comment by Asaaj** [comment]
@kirkshoop with C++20 approaching completion on all major compilers, it would be great to get this fix tested and released soon so this library doesn't gate those who want to upgrade (myself included).

**Comment by david-alvarez-rosa** [comment]
Thanks!!

**Pull request merged**
